title: Deng                 # title of the site
description: Less is more.  # description of the site

# Default layout
defaults:
  - scope:
      path: ""
    values:
      layout: "post"

# Social
zhihu: professordeng
bilibili: 491275843
github: professordeng
email: professordeng@qq.com